### ISSUE TITLE
ask: software HSS

### ISSUE THREAD

**Issue by cahya1123** [hidrokit/hidrokit#113]
bang, ada rencana bikin software HSS?

**Comment by taruma** [comment]
Sebenarnya ada rencana buat modul untuk HSS yang ngikutin SNI. Saya sempat buat isu #97 tentang HSS. Tapi berhubung saya sudah [_move on_](https://medium.com/@taruma/hidrokit-pada-tahun-2020-c00cd8860c0e) di proyek ini, gak saya lanjutin lagi.
